### ISSUE TITLE
Issues in dark mode

### ISSUE THREAD

**Issue by bohemima** [mmerlijn/nova-rrule-field#1]
Hi, just found this package, not sure of you are still working on it but there is an issue in dark mode, see attached screenshot

<img width="1151" alt="image" src="https://github.com/mmerlijn/nova-rrule-field/assets/195410/d33da4c3-5d53-4076-bc43-2fc12740284d">

**Comment by mmerlijn** [comment]
I have fixed the dark mode issue in the new version
